1                  TURBO Pascal installation menu.
2           Choose installation item from the following:
3 
4 [S]creen installation   |   [C]ommand installation   |   [Q]uit
5 
6                        Enter S, C, or Q:
10 Duplicate definition. Error occurred between question
11 Commands starting with the same letter must have the same length.
   Error occurred between question
12 The total maximum length of commands are execeeded
13  ->


14 CURSOR MOVEMENTS:

20  Character left               
21    Alternative                
22  Character right              
23  Word left                    
24  Word right                   
25  Line up                      
26  Line down                    
27  Scroll down                  
28  Scroll up                    
29  Page up                      
30  Page down                    
31  To left on line              
32  To right on line             
33  To top of page               
34  To bottom of page            
35  To top of file               
36  To end of file               
37  To begining of block         
38  To end of block              
39  To last cursor position      


15 INSERT & DELETE:

40  Insert mode on/off           
41  Insert line                  
42  Delete line                  
43  Delete to end of line        
44  Delete right word            
45  Delete character under cursor
46  Delete left character        
47    Alternative                


16 BLOCK COMMANDS:

48  Mark block begin             
49  Mark block end               
50  Mark single word             
51  Hide/display block           
52  Copy block                   
53  Move block                   
54  Delete block                 
55  Read block from disk         
56  Write block to disk          


17 MISC. EDITING COMMANDS:  

57  End edit                     
58  Tab                          
59  Auto tab on/off              
60  Restore line                 
61  Find                         
62  Find & replace               
63  Repeat last find             
64  Control character prefix     

101 Nothing
 ^Q: Quit, ^R: Last page, ^C: Next page, <RETURN>: Select terminal:
 Wait Sorting Definitions
 Change to:
 (Y/N)? 
 y
 n
 Text file name:
 Command:
 Numeric entry expected
 Legal range is 
 , please re-enter: 
 Choose one of the following terminals:
 None of the above   ( Max. 20 Characters )
 Delete a definition ( Max. 20 Characters )
 Which terminal? (Enter no. or ^Q to exit): 
 Delete terminal? (Enter no. or ^Q to exit):
 Do you want to modify this definition before installation? 
 Terminal type:
 Send an initialization string to the terminal?
 Initializaion defined as a command string? (No = a file)
 Send a reset string to the terminal
 Reset defined as a command? (No = a file)
 CURSOR LEAD-IN command: 
 CURSOR POSITIONING COMMAND to send between line and column:   
 CURSOR POSITIONING COMMAND to send after both line and column:
 Column first
 OFFSET to add to LINE:  
 OFFSET to add to COLUMN:
 Binary address
 Number of ASCII digits (2 or 3): 
 CLEAR SCREEN command: 
 Does CLEAR SCREEN also HOME cursor
 HOME command: 
 DELETE LINE command: 
 INSERT LINE command: 
 ERASE TO END OF LINE command:
 START HIGHLIGHTING command:  
 END HIGHLIGHTING command:    
 Number of rows (lines) on your screen: 
 Number of columns on your screen:      
 Delay after CURSOR ADDRESS (0-255 ms):                     
 Delay after CLEAR, DELETE and INSERT (0-255 ms):           
 Delay after ERASE TO END OF LINE and HIGHLIGHT (0-255 ms): 
 Is this definition correct?
                     Hardware dependent information
 Operating frequency of your microprocessor in MHz (for delays):
pendent information
 Operating frequency of your microprocessor in MHz (for delays):
